### ISSUE TITLE
Not compatible with Django 1.10-style middleware

### ISSUE THREAD

**Issue by fladi** [benoitbryon/django-downloadview#136]
Django 1.10 introduced the [new `MIDDLEWARE` setting](https://docs.djangoproject.com/en/1.10/topics/http/middleware/#) which makes some assumptions about the `__init__` methdo of a middleware class. All middleware classes in django-downloadview depend on named arguments in their `__init__` method that are populated with unexpeted values, like other middlewares or the Django core Basehandler.

**Comment by Natim** [comment]
I guess this was fixed with the support for Django 1.11+, feel free to open a new issue if it doesn't.
