### ISSUE TITLE
mI got the following error while running the demo with "make runserver":django.db.utils.OperationalError: Problem installing fixture '/home/ruihai.jing/TTProgram/django-downloadview-master/demo/demoproject/fixtures/demo.json': Could not load object.Document(pk=1): no such table: object_document

### ISSUE THREAD

**Issue by ruihai-jing** [benoitbryon/django-downloadview#157]
django.db.utils.OperationalError: Problem installing fixture '/home/ruihai.jing/TTProgram/django-downloadview-master/demo/demoproject/fixtures/demo.json': Could not load object.Document(pk=1): no such table: object_document

**Comment by Natim** [comment]
You need to run `./manage.py migrate` to create the demo database.
