### ISSUE TITLE
Support status

### ISSUE THREAD

**Issue by spectras** [benoitbryon/django-downloadview#96]
Hello @benoitbryon,

I am in the process of choosing either a module or a custom implementation for returning files through Django. Or rather, telling the rproxy to do it. Django-downloadview looks really good, the splitting of responsibility using a response subclass and a configurable middleware is exactly what I had in mind.

So... the question: what is the support status of downloadview?
Graphs show little change over the last few months and lack of tests make it difficult to assess compatibility with future Django releases. As good as it may be, if I must maintain code myself, I'd rather maintain my own, reduced-scope, code.

**Comment by Natim** [comment]
We use it in production for multiple projects it could be very good if you
could contribute and we will make our best to help if you do.

**Comment by spectras** [comment]
Alright thanks for the fast answer.
I won't make promises, but if I have time to contribute, expect test cases.

**Comment by benoitbryon** [comment]
> lack of tests make it difficult to assess compatibility with future Django releases

Agreed. We are working on upgrading our (quite big) production projects to latest Django releases... so compatibility of libraries is on the roadmap.
